project_name: Build sing-box

before:
  hooks:
    - go mod tidy -v

builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -v
      - -trimpath
    tags:
      - with_quic
      - with_grpc
      - with_dhcp
      - with_wireguard
      - with_ech
      - with_utls
      - with_reality_server
      - with_acme
      - with_clash_api
      - with_v2ray_api
      - with_gvisor
    ldflags:
      - -s -w -X github.com/SagerNet/sing-box/constant.Version=$SB_VERSION
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm
      - arm64
      - 386
      - amd64
      - mips
      - mipsle
      - s390x
      - riscv64
    gomips:
      - softfloat
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    main: ./cmd/sing-box/
    binary: sing-box

universal_binaries:
  - name_template: "sing-box"
    replace: false

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "sing-box"

archives:
  - name_template: "sing-box_{{ .Os }}_{{ .Arch }}"
    files:
      - none*

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore"
      - Merge pull request
      - Merge branch
      - go mod tidy
