name: "4. Build & Pull latest release"

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["3. Change Version"]
    branches: [main]
    types:
      - completed

jobs:
  Sing-box:
    name: Cross compile Sing-box
    runs-on: ubuntu-20.04
    env:
      workdir: sing-box-source

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check the latest verion
        run: |
          [ -e README.md ] && NOW=$(awk '/^ - ### \*\*latest\*\*:/{print $NF}' README.md)
          LATEST=$(wget -qO- "https://api.github.com/repos/SagerNet/sing-box/releases/latest" | awk -F '"' '/tag_name/{print $4}')
          echo " NOW: $NOW"
          echo " LATEST: $LATEST"
          if [ "$NOW" != "$LATEST" ]; then
            echo "VERSION=$LATEST" >> $GITHUB_ENV
          fi

      - name: Git clone sing-box
        if: ${{ env.VERSION != '' }}
        run: |
          git clone --branch ${{ env.VERSION }} https://github.com/SagerNet/sing-box.git ${{ env.workdir }}
          cp .github/sing-box.yml ${{ env.workdir }}/.goreleaser.yml
          sed -i "s/ChangeSingBoxVersion/$LATEST/" ${{ env.workdir }}/.goreleaser.yml

      - name: Set up GoReleaser
        if: ${{ env.VERSION != '' }}
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Run GoReleaser
        if: ${{ env.VERSION != '' }}
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          workdir: ${{ env.workdir }}
          args: --auto-snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release binaries
        if: ${{ env.VERSION != '' }}
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ env.VERSION }}
          prerelease: false
          files: ${{ env.workdir }}/dist/*.tar.gz
