name: "1. Build latest images & Pull Release"

on:
  workflow_dispatch:
  schedule:
    - cron: 0 */12 * * *

jobs:
  docker_pull:
    runs-on: ubuntu-latest
    name: "Build image & Pull Release"
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKERHUB_REPOSITORY: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check the latest verion
        run: |
          [ -e README.md ] && NOW=$(awk '/^ - ### \*\*latest\*\*:/{print $NF}' README.md)
          LATEST=$(wget -qO- "https://api.github.com/repos/SagerNet/sing-box/releases/latest" | awk -F '"' '/tag_name/{print $4}')
          echo " NOW: $NOW"
          echo " LATEST: $LATEST"
          if [ "$NOW" != "$LATEST" ]; then
            sed -i "/^ - ### \*\*latest\*\*:/s/\(.*: \).*/\1$LATEST/" README.md
            echo "VERSION=$LATEST" >> $GITHUB_ENV
          fi

      # - name: Change working directory
      #   if: ${{ env.VERSION != '' }}
      #   run: |
      #     mkdir -p build/sb
      #     cd build/sb
      #     git clone --branch ${{ env.VERSION }} --single-branch https://github.com/SagerNet/sing-box.git sing-box
      #     ls -la
      #     cd sing-box
      #     export SB_COMMIT=$(git rev-parse --short HEAD)
      #     export SB_VERSION=$(go run ./cmd/internal/read_tag)
      #     echo "SB_COMMIT: $SB_COMMIT"
      #     echo "SB_VERSION: $SB_VERSION"

      - name: Checkout SagerNet/sing-box
        uses: actions/checkout@v4
        with:
          repository: SagerNet/sing-box
          ref: main-next
          path: sing-box

      - name: Checkout code crazy-max/ghaction-xgo
        uses: actions/checkout@v4
        with:
          repository: crazy-max/ghaction-xgo
          fetch-depth: 0

      - name: xgo build
        if: ${{ env.VERSION != '' }}
        uses: crazy-max/ghaction-xgo@v3
        with:
          xgo_version: latest
          go_version: latest
          dest: dist
          prefix: sing-box
          targets: linux/amd64,linux/arm64,linux/arm-7
          # v: true
          # x: false
          # race: false
          # tags: with_quic,with_grpc,with_dhcp,with_wireguard,with_ech,with_utls,with_reality_server,with_acme,with_clash_api,with_v2ray_api,with_gvisor
          # ldflags: -s -w --extldflags '-static -fpic' -X github.com/SagerNet/sing-box/constant.Version=$VERSION
          # buildmode: default

      - name: fix dist
        if: ${{ env.VERSION != '' }}
        run: |
          mv dist/dashboard-linux-arm-7 dist/dashboard-linux-arm

      - name: Compress dist files
        if: ${{ env.VERSION != '' }}
        run: |
          for file in dist/*; do
            if [ -f "$file" ]; then
              zip -r "$file.zip" "$file"
            fi
          done

      - name: Release
        if: ${{ env.VERSION != '' }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.zip"
          generateReleaseNotes: true
